services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  etl:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      API_URL: https://jsonplaceholder.typicode.com/posts
      EXTRACT_SCHEDULE: "*/1 * * * *"
      TRANSFORM_SCHEDULE: "*/2 * * * *"
    depends_on:
      - db
    volumes:
      - ./scripts:/app/scripts
      - ./sql:/app/sql
      - ./logs:/var/log/cron
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data: